version: "3"
services:
  app:
    build: .
    ports:
      - "5200:3400"
    volumes:
      - .:/app
      - /app/node_modules/
    links:
      - mongo
    depends_on:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"